language: go

go:
  - 1.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev
  - go get github.com/gotk3/gotk3/gtk
  - go install -tags gtk_3_18 github.com/gotk3/gotk3/gtk

script:
  - make
